---

# See https://cert-manager.io/docs/installation/kubernetes/

- name: Sanity check
  assert:
    that:
    - cm_letsencrypt_email is defined
    - cm_letsencrypt_email != 'SetMe'

- name: Deploy cert-manager
  k8s:
    definition: "{{ lookup('file', '{{ item }}.yml') }}"
    wait: yes
    wait_timeout: "{{ cm_wait_timeout }}"
  loop:
  - cert-manager-0-12-0

- name: Deploy ClusterIssuer
  k8s:
    definition: "{{ lookup('template', '{{ item }}.yml.j2') }}"
    wait: yes
    wait_timeout: "{{ cm_wait_timeout }}"
  loop:
  - clusterissuer
